// Code generated by mockery v2.52.2. DO NOT EDIT.

package validatormocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// MockFieldLevel is an autogenerated mock type for the FieldLevel type
type MockFieldLevel struct {
	mock.Mock
}

type MockFieldLevel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFieldLevel) EXPECT() *MockFieldLevel_Expecter {
	return &MockFieldLevel_Expecter{mock: &_m.Mock}
}

// ExtractType provides a mock function with given fields: field
func (_m *MockFieldLevel) ExtractType(field reflect.Value) (reflect.Value, reflect.Kind, bool) {
	ret := _m.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for ExtractType")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	if rf, ok := ret.Get(0).(func(reflect.Value) (reflect.Value, reflect.Kind, bool)); ok {
		return rf(field)
	}
	if rf, ok := ret.Get(0).(func(reflect.Value) reflect.Value); ok {
		r0 = rf(field)
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	if rf, ok := ret.Get(1).(func(reflect.Value) reflect.Kind); ok {
		r1 = rf(field)
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}

	if rf, ok := ret.Get(2).(func(reflect.Value) bool); ok {
		r2 = rf(field)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockFieldLevel_ExtractType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractType'
type MockFieldLevel_ExtractType_Call struct {
	*mock.Call
}

// ExtractType is a helper method to define mock.On call
//   - field reflect.Value
func (_e *MockFieldLevel_Expecter) ExtractType(field interface{}) *MockFieldLevel_ExtractType_Call {
	return &MockFieldLevel_ExtractType_Call{Call: _e.mock.On("ExtractType", field)}
}

func (_c *MockFieldLevel_ExtractType_Call) Run(run func(field reflect.Value)) *MockFieldLevel_ExtractType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Value))
	})
	return _c
}

func (_c *MockFieldLevel_ExtractType_Call) Return(value reflect.Value, kind reflect.Kind, nullable bool) *MockFieldLevel_ExtractType_Call {
	_c.Call.Return(value, kind, nullable)
	return _c
}

func (_c *MockFieldLevel_ExtractType_Call) RunAndReturn(run func(reflect.Value) (reflect.Value, reflect.Kind, bool)) *MockFieldLevel_ExtractType_Call {
	_c.Call.Return(run)
	return _c
}

// Field provides a mock function with no fields
func (_m *MockFieldLevel) Field() reflect.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Field")
	}

	var r0 reflect.Value
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	return r0
}

// MockFieldLevel_Field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Field'
type MockFieldLevel_Field_Call struct {
	*mock.Call
}

// Field is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) Field() *MockFieldLevel_Field_Call {
	return &MockFieldLevel_Field_Call{Call: _e.mock.On("Field")}
}

func (_c *MockFieldLevel_Field_Call) Run(run func()) *MockFieldLevel_Field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_Field_Call) Return(_a0 reflect.Value) *MockFieldLevel_Field_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_Field_Call) RunAndReturn(run func() reflect.Value) *MockFieldLevel_Field_Call {
	_c.Call.Return(run)
	return _c
}

// FieldName provides a mock function with no fields
func (_m *MockFieldLevel) FieldName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FieldName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFieldLevel_FieldName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldName'
type MockFieldLevel_FieldName_Call struct {
	*mock.Call
}

// FieldName is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) FieldName() *MockFieldLevel_FieldName_Call {
	return &MockFieldLevel_FieldName_Call{Call: _e.mock.On("FieldName")}
}

func (_c *MockFieldLevel_FieldName_Call) Run(run func()) *MockFieldLevel_FieldName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_FieldName_Call) Return(_a0 string) *MockFieldLevel_FieldName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_FieldName_Call) RunAndReturn(run func() string) *MockFieldLevel_FieldName_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructFieldOK provides a mock function with no fields
func (_m *MockFieldLevel) GetStructFieldOK() (reflect.Value, reflect.Kind, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStructFieldOK")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	if rf, ok := ret.Get(0).(func() (reflect.Value, reflect.Kind, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	if rf, ok := ret.Get(1).(func() reflect.Kind); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}

	if rf, ok := ret.Get(2).(func() bool); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockFieldLevel_GetStructFieldOK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructFieldOK'
type MockFieldLevel_GetStructFieldOK_Call struct {
	*mock.Call
}

// GetStructFieldOK is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) GetStructFieldOK() *MockFieldLevel_GetStructFieldOK_Call {
	return &MockFieldLevel_GetStructFieldOK_Call{Call: _e.mock.On("GetStructFieldOK")}
}

func (_c *MockFieldLevel_GetStructFieldOK_Call) Run(run func()) *MockFieldLevel_GetStructFieldOK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOK_Call) Return(_a0 reflect.Value, _a1 reflect.Kind, _a2 bool) *MockFieldLevel_GetStructFieldOK_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOK_Call) RunAndReturn(run func() (reflect.Value, reflect.Kind, bool)) *MockFieldLevel_GetStructFieldOK_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructFieldOK2 provides a mock function with no fields
func (_m *MockFieldLevel) GetStructFieldOK2() (reflect.Value, reflect.Kind, bool, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStructFieldOK2")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	var r3 bool
	if rf, ok := ret.Get(0).(func() (reflect.Value, reflect.Kind, bool, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	if rf, ok := ret.Get(1).(func() reflect.Kind); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}

	if rf, ok := ret.Get(2).(func() bool); ok {
		r2 = rf()
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func() bool); ok {
		r3 = rf()
	} else {
		r3 = ret.Get(3).(bool)
	}

	return r0, r1, r2, r3
}

// MockFieldLevel_GetStructFieldOK2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructFieldOK2'
type MockFieldLevel_GetStructFieldOK2_Call struct {
	*mock.Call
}

// GetStructFieldOK2 is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) GetStructFieldOK2() *MockFieldLevel_GetStructFieldOK2_Call {
	return &MockFieldLevel_GetStructFieldOK2_Call{Call: _e.mock.On("GetStructFieldOK2")}
}

func (_c *MockFieldLevel_GetStructFieldOK2_Call) Run(run func()) *MockFieldLevel_GetStructFieldOK2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOK2_Call) Return(_a0 reflect.Value, _a1 reflect.Kind, _a2 bool, _a3 bool) *MockFieldLevel_GetStructFieldOK2_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOK2_Call) RunAndReturn(run func() (reflect.Value, reflect.Kind, bool, bool)) *MockFieldLevel_GetStructFieldOK2_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructFieldOKAdvanced provides a mock function with given fields: val, namespace
func (_m *MockFieldLevel) GetStructFieldOKAdvanced(val reflect.Value, namespace string) (reflect.Value, reflect.Kind, bool) {
	ret := _m.Called(val, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetStructFieldOKAdvanced")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	if rf, ok := ret.Get(0).(func(reflect.Value, string) (reflect.Value, reflect.Kind, bool)); ok {
		return rf(val, namespace)
	}
	if rf, ok := ret.Get(0).(func(reflect.Value, string) reflect.Value); ok {
		r0 = rf(val, namespace)
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	if rf, ok := ret.Get(1).(func(reflect.Value, string) reflect.Kind); ok {
		r1 = rf(val, namespace)
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}

	if rf, ok := ret.Get(2).(func(reflect.Value, string) bool); ok {
		r2 = rf(val, namespace)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockFieldLevel_GetStructFieldOKAdvanced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructFieldOKAdvanced'
type MockFieldLevel_GetStructFieldOKAdvanced_Call struct {
	*mock.Call
}

// GetStructFieldOKAdvanced is a helper method to define mock.On call
//   - val reflect.Value
//   - namespace string
func (_e *MockFieldLevel_Expecter) GetStructFieldOKAdvanced(val interface{}, namespace interface{}) *MockFieldLevel_GetStructFieldOKAdvanced_Call {
	return &MockFieldLevel_GetStructFieldOKAdvanced_Call{Call: _e.mock.On("GetStructFieldOKAdvanced", val, namespace)}
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced_Call) Run(run func(val reflect.Value, namespace string)) *MockFieldLevel_GetStructFieldOKAdvanced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Value), args[1].(string))
	})
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced_Call) Return(_a0 reflect.Value, _a1 reflect.Kind, _a2 bool) *MockFieldLevel_GetStructFieldOKAdvanced_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced_Call) RunAndReturn(run func(reflect.Value, string) (reflect.Value, reflect.Kind, bool)) *MockFieldLevel_GetStructFieldOKAdvanced_Call {
	_c.Call.Return(run)
	return _c
}

// GetStructFieldOKAdvanced2 provides a mock function with given fields: val, namespace
func (_m *MockFieldLevel) GetStructFieldOKAdvanced2(val reflect.Value, namespace string) (reflect.Value, reflect.Kind, bool, bool) {
	ret := _m.Called(val, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetStructFieldOKAdvanced2")
	}

	var r0 reflect.Value
	var r1 reflect.Kind
	var r2 bool
	var r3 bool
	if rf, ok := ret.Get(0).(func(reflect.Value, string) (reflect.Value, reflect.Kind, bool, bool)); ok {
		return rf(val, namespace)
	}
	if rf, ok := ret.Get(0).(func(reflect.Value, string) reflect.Value); ok {
		r0 = rf(val, namespace)
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	if rf, ok := ret.Get(1).(func(reflect.Value, string) reflect.Kind); ok {
		r1 = rf(val, namespace)
	} else {
		r1 = ret.Get(1).(reflect.Kind)
	}

	if rf, ok := ret.Get(2).(func(reflect.Value, string) bool); ok {
		r2 = rf(val, namespace)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(reflect.Value, string) bool); ok {
		r3 = rf(val, namespace)
	} else {
		r3 = ret.Get(3).(bool)
	}

	return r0, r1, r2, r3
}

// MockFieldLevel_GetStructFieldOKAdvanced2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStructFieldOKAdvanced2'
type MockFieldLevel_GetStructFieldOKAdvanced2_Call struct {
	*mock.Call
}

// GetStructFieldOKAdvanced2 is a helper method to define mock.On call
//   - val reflect.Value
//   - namespace string
func (_e *MockFieldLevel_Expecter) GetStructFieldOKAdvanced2(val interface{}, namespace interface{}) *MockFieldLevel_GetStructFieldOKAdvanced2_Call {
	return &MockFieldLevel_GetStructFieldOKAdvanced2_Call{Call: _e.mock.On("GetStructFieldOKAdvanced2", val, namespace)}
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced2_Call) Run(run func(val reflect.Value, namespace string)) *MockFieldLevel_GetStructFieldOKAdvanced2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Value), args[1].(string))
	})
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced2_Call) Return(_a0 reflect.Value, _a1 reflect.Kind, _a2 bool, _a3 bool) *MockFieldLevel_GetStructFieldOKAdvanced2_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockFieldLevel_GetStructFieldOKAdvanced2_Call) RunAndReturn(run func(reflect.Value, string) (reflect.Value, reflect.Kind, bool, bool)) *MockFieldLevel_GetStructFieldOKAdvanced2_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with no fields
func (_m *MockFieldLevel) GetTag() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFieldLevel_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockFieldLevel_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) GetTag() *MockFieldLevel_GetTag_Call {
	return &MockFieldLevel_GetTag_Call{Call: _e.mock.On("GetTag")}
}

func (_c *MockFieldLevel_GetTag_Call) Run(run func()) *MockFieldLevel_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_GetTag_Call) Return(_a0 string) *MockFieldLevel_GetTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_GetTag_Call) RunAndReturn(run func() string) *MockFieldLevel_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// Param provides a mock function with no fields
func (_m *MockFieldLevel) Param() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Param")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFieldLevel_Param_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Param'
type MockFieldLevel_Param_Call struct {
	*mock.Call
}

// Param is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) Param() *MockFieldLevel_Param_Call {
	return &MockFieldLevel_Param_Call{Call: _e.mock.On("Param")}
}

func (_c *MockFieldLevel_Param_Call) Run(run func()) *MockFieldLevel_Param_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_Param_Call) Return(_a0 string) *MockFieldLevel_Param_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_Param_Call) RunAndReturn(run func() string) *MockFieldLevel_Param_Call {
	_c.Call.Return(run)
	return _c
}

// Parent provides a mock function with no fields
func (_m *MockFieldLevel) Parent() reflect.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Parent")
	}

	var r0 reflect.Value
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	return r0
}

// MockFieldLevel_Parent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parent'
type MockFieldLevel_Parent_Call struct {
	*mock.Call
}

// Parent is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) Parent() *MockFieldLevel_Parent_Call {
	return &MockFieldLevel_Parent_Call{Call: _e.mock.On("Parent")}
}

func (_c *MockFieldLevel_Parent_Call) Run(run func()) *MockFieldLevel_Parent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_Parent_Call) Return(_a0 reflect.Value) *MockFieldLevel_Parent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_Parent_Call) RunAndReturn(run func() reflect.Value) *MockFieldLevel_Parent_Call {
	_c.Call.Return(run)
	return _c
}

// StructFieldName provides a mock function with no fields
func (_m *MockFieldLevel) StructFieldName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StructFieldName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFieldLevel_StructFieldName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StructFieldName'
type MockFieldLevel_StructFieldName_Call struct {
	*mock.Call
}

// StructFieldName is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) StructFieldName() *MockFieldLevel_StructFieldName_Call {
	return &MockFieldLevel_StructFieldName_Call{Call: _e.mock.On("StructFieldName")}
}

func (_c *MockFieldLevel_StructFieldName_Call) Run(run func()) *MockFieldLevel_StructFieldName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_StructFieldName_Call) Return(_a0 string) *MockFieldLevel_StructFieldName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_StructFieldName_Call) RunAndReturn(run func() string) *MockFieldLevel_StructFieldName_Call {
	_c.Call.Return(run)
	return _c
}

// Top provides a mock function with no fields
func (_m *MockFieldLevel) Top() reflect.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Top")
	}

	var r0 reflect.Value
	if rf, ok := ret.Get(0).(func() reflect.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(reflect.Value)
	}

	return r0
}

// MockFieldLevel_Top_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Top'
type MockFieldLevel_Top_Call struct {
	*mock.Call
}

// Top is a helper method to define mock.On call
func (_e *MockFieldLevel_Expecter) Top() *MockFieldLevel_Top_Call {
	return &MockFieldLevel_Top_Call{Call: _e.mock.On("Top")}
}

func (_c *MockFieldLevel_Top_Call) Run(run func()) *MockFieldLevel_Top_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFieldLevel_Top_Call) Return(_a0 reflect.Value) *MockFieldLevel_Top_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldLevel_Top_Call) RunAndReturn(run func() reflect.Value) *MockFieldLevel_Top_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFieldLevel creates a new instance of MockFieldLevel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFieldLevel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFieldLevel {
	mock := &MockFieldLevel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
