// Code generated by mockery v2.52.2. DO NOT EDIT.

package v1mocks

import (
	context "context"
	dto "ums/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUMS is an autogenerated mock type for the UMS type
type MockUMS struct {
	mock.Mock
}

type MockUMS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUMS) EXPECT() *MockUMS_Expecter {
	return &MockUMS_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, createUser
func (_m *MockUMS) CreateUser(ctx context.Context, createUser dto.CreateUserRequest) (uuid.UUID, error) {
	ret := _m.Called(ctx, createUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) (uuid.UUID, error)); ok {
		return rf(ctx, createUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) uuid.UUID); ok {
		r0 = rf(ctx, createUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserRequest) error); ok {
		r1 = rf(ctx, createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUMS_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUMS_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - createUser dto.CreateUserRequest
func (_e *MockUMS_Expecter) CreateUser(ctx interface{}, createUser interface{}) *MockUMS_CreateUser_Call {
	return &MockUMS_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, createUser)}
}

func (_c *MockUMS_CreateUser_Call) Run(run func(ctx context.Context, createUser dto.CreateUserRequest)) *MockUMS_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateUserRequest))
	})
	return _c
}

func (_c *MockUMS_CreateUser_Call) Return(_a0 uuid.UUID, _a1 error) *MockUMS_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUMS_CreateUser_Call) RunAndReturn(run func(context.Context, dto.CreateUserRequest) (uuid.UUID, error)) *MockUMS_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserWithRole provides a mock function with given fields: ctx, createUser
func (_m *MockUMS) CreateUserWithRole(ctx context.Context, createUser dto.CreateUserWithRoleRequest) (uuid.UUID, error) {
	ret := _m.Called(ctx, createUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserWithRole")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserWithRoleRequest) (uuid.UUID, error)); ok {
		return rf(ctx, createUser)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateUserWithRoleRequest) uuid.UUID); ok {
		r0 = rf(ctx, createUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateUserWithRoleRequest) error); ok {
		r1 = rf(ctx, createUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUMS_CreateUserWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserWithRole'
type MockUMS_CreateUserWithRole_Call struct {
	*mock.Call
}

// CreateUserWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - createUser dto.CreateUserWithRoleRequest
func (_e *MockUMS_Expecter) CreateUserWithRole(ctx interface{}, createUser interface{}) *MockUMS_CreateUserWithRole_Call {
	return &MockUMS_CreateUserWithRole_Call{Call: _e.mock.On("CreateUserWithRole", ctx, createUser)}
}

func (_c *MockUMS_CreateUserWithRole_Call) Run(run func(ctx context.Context, createUser dto.CreateUserWithRoleRequest)) *MockUMS_CreateUserWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateUserWithRoleRequest))
	})
	return _c
}

func (_c *MockUMS_CreateUserWithRole_Call) Return(_a0 uuid.UUID, _a1 error) *MockUMS_CreateUserWithRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUMS_CreateUserWithRole_Call) RunAndReturn(run func(context.Context, dto.CreateUserWithRoleRequest) (uuid.UUID, error)) *MockUMS_CreateUserWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, uid
func (_m *MockUMS) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUMS_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUMS_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockUMS_Expecter) DeleteUser(ctx interface{}, uid interface{}) *MockUMS_DeleteUser_Call {
	return &MockUMS_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, uid)}
}

func (_c *MockUMS_DeleteUser_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockUMS_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUMS_DeleteUser_Call) Return(_a0 error) *MockUMS_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUMS_DeleteUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUMS_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUser provides a mock function with given fields: ctx, uid
func (_m *MockUMS) ReadUser(ctx context.Context, uid uuid.UUID) (dto.ReadUserResponse, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for ReadUser")
	}

	var r0 dto.ReadUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.ReadUserResponse, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.ReadUserResponse); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(dto.ReadUserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUMS_ReadUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUser'
type MockUMS_ReadUser_Call struct {
	*mock.Call
}

// ReadUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockUMS_Expecter) ReadUser(ctx interface{}, uid interface{}) *MockUMS_ReadUser_Call {
	return &MockUMS_ReadUser_Call{Call: _e.mock.On("ReadUser", ctx, uid)}
}

func (_c *MockUMS_ReadUser_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockUMS_ReadUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUMS_ReadUser_Call) Return(_a0 dto.ReadUserResponse, _a1 error) *MockUMS_ReadUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUMS_ReadUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (dto.ReadUserResponse, error)) *MockUMS_ReadUser_Call {
	_c.Call.Return(run)
	return _c
}

// ReadUsers provides a mock function with given fields: ctx
func (_m *MockUMS) ReadUsers(ctx context.Context) (dto.ReadUsersResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadUsers")
	}

	var r0 dto.ReadUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dto.ReadUsersResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dto.ReadUsersResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dto.ReadUsersResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUMS_ReadUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadUsers'
type MockUMS_ReadUsers_Call struct {
	*mock.Call
}

// ReadUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUMS_Expecter) ReadUsers(ctx interface{}) *MockUMS_ReadUsers_Call {
	return &MockUMS_ReadUsers_Call{Call: _e.mock.On("ReadUsers", ctx)}
}

func (_c *MockUMS_ReadUsers_Call) Run(run func(ctx context.Context)) *MockUMS_ReadUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUMS_ReadUsers_Call) Return(_a0 dto.ReadUsersResponse, _a1 error) *MockUMS_ReadUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUMS_ReadUsers_Call) RunAndReturn(run func(context.Context) (dto.ReadUsersResponse, error)) *MockUMS_ReadUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserData provides a mock function with given fields: ctx, uid, userData
func (_m *MockUMS) UpdateUserData(ctx context.Context, uid uuid.UUID, userData interface{}) error {
	ret := _m.Called(ctx, uid, userData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, interface{}) error); ok {
		r0 = rf(ctx, uid, userData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUMS_UpdateUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserData'
type MockUMS_UpdateUserData_Call struct {
	*mock.Call
}

// UpdateUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - userData interface{}
func (_e *MockUMS_Expecter) UpdateUserData(ctx interface{}, uid interface{}, userData interface{}) *MockUMS_UpdateUserData_Call {
	return &MockUMS_UpdateUserData_Call{Call: _e.mock.On("UpdateUserData", ctx, uid, userData)}
}

func (_c *MockUMS_UpdateUserData_Call) Run(run func(ctx context.Context, uid uuid.UUID, userData interface{})) *MockUMS_UpdateUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(interface{}))
	})
	return _c
}

func (_c *MockUMS_UpdateUserData_Call) Return(_a0 error) *MockUMS_UpdateUserData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUMS_UpdateUserData_Call) RunAndReturn(run func(context.Context, uuid.UUID, interface{}) error) *MockUMS_UpdateUserData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUMS creates a new instance of MockUMS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUMS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUMS {
	mock := &MockUMS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
